apiVersion: v1
kind: Namespace
metadata:
  name: finance-arik
---
apiVersion: v1
kind: Pod
metadata:
  name: temp-bus
  namespace: finance-arik
spec:
  containers:
    - name: redis
      image: redis:alpine
