apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
      image: nginx
      env:
        - name: KEY1
          valueFrom:
            configMapKeyRef:
              name: keyvalcfgmap
              key: key1
        - name: KEY2
          valueFrom:
            configMapKeyRef:
              name: keyvalcfgmap
              key: key2
