apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: use-pv
    name: use-pvspec-arik
spec:
  volumes:
    - name: pv-1
      persistentVolumeClaim:
        claimName: pv-claim-1
  containers:
    - image: nginx
      name: use-pv
      volumeMounts:
        - name: pv-1
          mountPath: /data
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  status: {}
