apiVersion: v1
kind: Pod
metadata:
  name: redis-storage-arik
spec:
  containers:
    - name: redis
      image: redis:alpine
      volumeMounts:
        - name: redis-storage
          mountPath: /data/redis
  volumes:
    - name: redis-storage
      emptyDir: {}
